### PR TITLE
Update README.md, Upload backup builds

### PR DESCRIPTION
**Pull request by Twig6943**

### CODE REVIEW

**Comment by Twig6943** [comment]
pls

**Comment by Twig6943** [comment]
@daegalus, could you upload backup builds for Ubuntu, Fedora, and Arch to the releases tab, just in case the actions break or the files in actions expire? (Sorry if u were working on it and I said the same thing again)

**Comment by daegalus** [comment]
> @daegalus, could you upload backup builds for Ubuntu, Fedora, and Arch to the releases tab, just in case the actions break or the files in actions expire? (Sorry if u were working on it and I said the same thing again)

I am working on it, but it won't be done tonight. Maybe tomorrow. Just know Ubuntu doesn't work yet, so just Arch/Fedora builds

**Comment by Twig6943** [comment]
But I do remember ubuntu builds over at the actions tab (Still tyms for Arch/Fedora)

**Pull request merged**
